### ISSUE TITLE
 Variable "hit" not found.

### ISSUE THREAD

**Issue by rickykissoon** [Shopify/graphql-codegen#14]
The following error shows up when running my hydrogen site locally: 

```
[Codegen] Error: Variable "hit" not found. This might be a bug in @shopify/graphql-codegen, please report it. 

at normalizeOperation (node_modules/@shopify/graphql-codegen/dist/cjs/plugin.cjs:21:11)
at getDocumentRegistryChunk (node_modules/@shopify/graphql-codegen/dist/cjs/plugin.cjs:63:7)
at Object.plugin (node_modules/@shopify/graphql-codegen/dist/cjs/plugin.cjs:4:16)
at node_modules/@graphql-codegen/core/cjs/execute-plugin.js:35:54
at node_modules/@graphql-codegen/plugin-helpers/cjs/profiler.js:7:49
```

As far as I can tell there are no apparent issues. I will update this issue if I do find something.

**Comment by frandiox** [comment]
Hey 👋 
Can you submit a small reproduction? The query itself is not enough because the error is also related to the variables that contain the query.

The easiest way is probably forking this repo and modifying the [example](https://github.com/Shopify/graphql-codegen/blob/main/examples/app/index.ts) until `npm run codegen` breaks with your error.

**Comment by chrisfung2020** [comment]
I encountered the same issue; as long as there are variables embedded in GraphQL, graphql-codegen will throw an error:  "Variable "xxx" not found"

```
const query = `#graphql
      query automaticDiscountNode {
        automaticDiscountNode(id: "${id}") {
          id
          metafield(key: "${metafieldKey}", namespace: "${metafieldNamespace}") {
            id
            value
          }
        }
      }`;

```
